### ISSUE TITLE
Can't pull gated models from Kaggle within scripts.

### ISSUE THREAD

**Issue by antonpolishko** [Kaggle/kagglehub#146]
We have next code snippet that was working before:
```
import jax
import os
import keras
import keras_nlp

os.environ["KAGGLE_USERNAME"] = "<user>"
os.environ["KAGGLE_KEY"] = "<key>"

gemma_lm = keras_nlp.models.GemmaCausalLM.from_preset("gemma_7b_en")
<...>
```
Now the same scripts are getting authentication error:
```
ValueError: 403 Client Error.

You don't have permission to access resource at URL: https://www.kaggle.com/models/keras/gemma/keras/gemma_7b_en/2
Please make sure you are authenticated if you are trying to access a private resource or a resource requiring consent.
```
Same happens if I run in withing Google Colab. You will need to install a few dependencies first
```
%pip install keras-nlp
%pip install -U keras, kagglehub 
```

The only way I was able to solve the error is to use 
```
import kagglehub
kagglehub.login()
```
within Google Colab (both hosted and local runtimes) and use the colab widget. I provided exactly the same credentials as in the code snippets above.

However this is not ideal, cause it's manual copy-paste of credentials and can't be used in pipelines. 

I tried `kagglehub==0.2.5` and latest `kagglehub==0.2.8`

**Comment by neshdev** [comment]
@antonpolishko - The issue is that you are not using the correct environment variable.

Please use `os.environ["KAGGLE_USERNAME"] = ...`

**Comment by antonpolishko** [comment]
@neshdev good catch. I'm actually using the correct "KAGGLE_USERNAME" in the code, otherwise it wouldn't work before :).

**Comment by antonpolishko** [comment]
Found a workaround for scripts. For a given environment you could still put kaggle.json to current user, f.e.

```
echo "{"username":"<username>","key":"<key>"}" > ~/.kaggle/kaggle.json
```

So as far as I'm concerned the issue could be closed.
