### ISSUE TITLE
Unable to download competition data from Google Colab

### ISSUE THREAD

**Issue by fbaltor** [Kaggle/kagglehub#169]
I cannot download the competition data into Google Colab even though I have the secrets correctly saved in the Colab Secrets:

![image](https://github.com/user-attachments/assets/364ecd20-08b3-46f2-b170-f3a17e31128b)

Checking [the commit that allowed the authentication in Colab using secrets](https://github.com/Kaggle/kagglehub/pull/157) I guess the problem is that despite the `KaggleApiV1Client` class being able to authenticate using the secrets, the `KaggleJwtClient` used by the `competition_download` is not authenticating with the new Colab secrets logic.

**Comment by fbaltor** [comment]
I saw that there is some work in this regard in the main branch, but I did not dig deep enough to check if it will solve the issue. I pip installed the main branch in the Colab but the problem persists.

**Comment by calderjo** [comment]
thanks for reaching out, this is intentional for all competition downloads. you must authenticate to ensure you have accepted rules.

https://github.com/Kaggle/kagglehub?tab=readme-ov-file#authenticate

**Comment by calderjo** [comment]
the colab secret issue should be addressed in 
https://github.com/Kaggle/kagglehub/pull/165

which should be apart of the latest release from yesterday

**Comment by fbaltor** [comment]
The issue is resolved!
