### ISSUE TITLE
CSV files are downloaded as zip when downloading as single file

### ISSUE THREAD

**Issue by leihuayi** [Kaggle/kagglehub#187]
When using kagglehub to download a single csv file, the file downloaded is written as a .csv but it is actually a zip, therefore the csv cannot be read.

Here is a example of script which reproduces the error, I give a link to a dataset but I noticed this error for other datasets with csv.

```python
import kagglehub
import pandas as pd

downloaded_path = kagglehub.dataset_download("jessicali9530/celeba-dataset", path="list_attr_celeba.csv")
df = pd.read_csv(downloaded_path)
```

error:
```bash
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 10: invalid continuation byte
```

This can be solved locally using the following:

```python
import kagglehub
import pandas as pd
import zipfile
import os

dataset_csv_path = kagglehub.dataset_download("jessicali9530/celeba-dataset", path="list_attr_celeba.csv")
os.rename(dataset_csv_path, dataset_csv_path + ".zip")
with zipfile.ZipFile(dataset_csv_path + ".zip", "r") as zip_ref:
    zip_ref.extractall(os.path.dirname(dataset_csv_path))

df = pd.read_csv(dataset_csv_path)
```
but it would be better that this fix be directly implemented within kagglehub library. This bug is actually due to kaggle-api which downloads the csv as a .csv.zip which can be seen when using the kaggle-api CLI.

**Comment by goeffthomas** [comment]
@leihuayi Thanks for raising this issue. I also just ran into this while developing a new feature and will be including a fix soon.
