### ISSUE TITLE
download data w/o auth!

### ISSUE THREAD

**Issue by innat** [Kaggle/kagglehub#94]
Posted something long ago, [here](https://www.kaggle.com/discussions/general/411551#2271668).

Shortly, we can do following without hassle. These are public resources. Can we do the same with kagglehub?

```python
images = keras.utils.get_file(
    origin="https://huggingface.co/datasets/images.tar.gz",
    untar=True,
)
```

or 

```python
hf_dataset_identifier = "{user_id}/data_id"
filename = "dataset.zip"
file_path = hf_hub_download(
    repo_id=hf_dataset_identifier, 
    filename=filename, 
    repo_type="dataset"
)
```

**Comment by neshdev** [comment]
Models will need users to be signed in, and in some cases, accept the terms of use agreement.
Datasets can be downloaded publicly, without being signed in.
